#!/usr/bin/env python
# -*- coding: utf-8 -*-
from typing import List

from documents import Query, Document


def search_with_bing(query: str) -> List[Document]: ...
def search_with_google(query: str) -> List[Document]: ...
def search_with_arxiv(query: str) -> List[Document]: ...
def search_with_wiki(query: str) -> List[Document]: ...
def generate_sub_query(query: str) -> List[Query]: ...
